spring:
  datasource:
    url: jdbc:mysql://localhost/java_shop
    username: travis
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    include: local
